set(SOURCES
	src/Positioners.h
	src/Positioners.cpp
	src/PositionData.h
	src/PositionData.cpp
	src/Scaleforms.h
	src/Scaleforms.cpp
	src/Inputs.h
	src/Inputs.cpp
	src/Utils.h
	src/Utils.cpp
	src/PCH.h
	src/main.cpp
)
